# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20170530_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nr', models.CharField(max_length=200)),
                ('product_comments', models.TextField()),
                ('address', models.CharField(max_length=200)),
                ('delivery_comments', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Customer')),
                ('delivery_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Delivery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Product')),
            ],
        ),
    ]
