# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20170531_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='instagram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
