# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20170622_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='password',
        ),
    ]
