# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-21 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20170626_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
