# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-04 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20170721_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_created',
            field=models.BooleanField(default=False),
        ),
    ]
