# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-04-22 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
    ]
